// This file was generated by Prisma and extended for NextOfKin.
// DATABASE_URL points to the pooled connection (pgBouncer) used at runtime.
// DIRECT_URL points to the direct Postgres connection used for migrations.
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_URL"],
  },
});
